name: Risk Analysis

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    #container: saraprager/test-examples:devsecops_github
    steps:
      - uses: actions/checkout@v3
      - uses: SaraPrager/DockerBasedAction@latest
      #- name: risk-analysis
      #  run: risk-analysis
