name: Risk Analysis

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: saraprager/test-examples:devsecops
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: risk-analysis
