name: Risk Analysis

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SaraPrager/DockerBasedAction@latest2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          CF_TENANT_ID: ${{ secrets.CF_TENANT_ID }}
